#theme: jekyll-theme-cayman

# Setup
title:        oye.sh
tagline:      没有伞的孩子，必须在雨中努力奔跑。
baseurl:      "http://oye.sh"
paginate:     10
locale:       "cn"
google_analytics:
show_downloads: false

# About/contact
author:
  name:       OYE
  url:        http://oye.sh

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown